include ../common/common.mk

init: create-key upload-config  ## Specific to this module. Create keypair and upload cloud-config. 
destroy: destroy-key ## Specific to this module. Destroy keypair.
.PHONY: destroy-key create-key upload-config
